pairing-bot.go

Currently the bot will accept `skip` and `unskip` with either a random second argument, or `skip tomorrow` followed by more arguments.

Don't accept random arguments for skip/unskip

---

pairing-bot.go
parseCmd.go
parseCmd_test.go

This PR adds unit tests for the `parseCmd` function.
The function was split out into a different file for easier navigation.
A custom errror type `parsingErr` was introduced, which maybe isn't strictly necessary but it might be helpful to have more differenciated errors as the project grows.
PR for running unit tests in GCP is upcoming.

Add unit tests for parseCmd

---

client.go
database.go
dispatch.go
main.go
pairing-bot.go

Interfaces will allow us to mock the DB and Zulip interaction, and have more unit tests.
This PR does the following:
* Split up code into several files
* Add interfaces ´RecurserDB´ for DB lookups of subscriber information, and ´APIAuthDB´ for DB lookups of API/authentication tokens. Move existing implementation of DB queries into ´FirestoreRecurserDB´ and ´FirestoreAPIAuthDB´ types implementing these interfaces.
* Add interfaces ´userRequest´ for handling user requests to the bot through the client (atm Zulip), and ´userNotification´ for sending notifications to users (e.g for matches and offboarding). Move existing implementation of client interaction into ´zulipUserRequest´ and ´zulipUserNotification´ types implementing these interfaces.
* Add ´PairingLogic´ type that holds the types …

Refactor with interfaces for DB and Zulip interaction

---

database.go
dispatch.go

Users are not guaranteed to be found in the firestore DB and as a result, there would be an empty map. Previously, the logic did not takes this into account and would try converting the empty map to a struct, ultimately panicking.
This PR will fix this by adding logic that creates a default Recruser struct in the case that no user was found in the DB.

Fix issue when the map is converted to a recurser struct

---

database.go
dispatch.go
pairing_bot.go
parse_cmd.go

#26 
- log instead of panicking (except for startup)
- log when handling an error, not when returning it
- make use of initialization statements in case of short asignment statements to `err`, like
```go
if err = pl.rdb.Set(ctx, userID, rec); err != nil {
...
}
```

Consistency in error handling

---

client.go
cron.yaml
database.go
dispatch.go
main.go
pairing_bot.go
parse_cmd.go

This PR adds the ability for Pairing Bot to post weekly checkins. These checkins will consist of 3 parts
1) How many recursers are currently subscribed to pairing bot.
2) The number of matches that pairing bot facilitated in the past week
3) A randomly selected review of pairing bot. [I still need to implement the ability for people to share feedback about pairing bot]
Through speaking with Recursers it seems like some of them hear about Pairing Bot during the first week but then forget to sign up. I think it would help to gently remind people about Pairing Bot and show them how it helps other people through these weekly checkins.

Adding Scaffolding for Pairing Bot Weekly Checkins

---

client.go
go.mod
go.sum

The low-hanging fruit for #55:
- Log filename and line, tweak comments on timezones
- Treat 400/500 HTTP responses from Zulip as errors
While I'm here, a couple cleanup things to get rid of the dependabot signal:
- Run go mod tidy
- Update dependencies, per dependabot
And one change I didn't make an explicit commit for:
- Resolve some of the lints about `ioutil.ReadAll` vs. `io.ReadAll`

Easy tweaks for issue 55

---

api.go
client.go
database.go
dispatch.go
pairing_bot.go
parse_cmd.go

Move towards using Zulip IDs instead of e-mails:
- Perform end-of-batch cleanup based on Zulip user ID rather than e-mail address
- Internally to the pairing database, consider "user ID" an int64 rather than a string
- Send messages based on user-ID rather than e-mail
And some cleanups:
- Cleanup: ioutil.ReadAll -> io.ReadAll
- Remove deprecated seeding of RNG

Use Zulip ID instead of e-mail for most things

---

api.go
client.go
database.go
dispatch.go
pairing_bot.go
parse_cmd.go

The history here is pretty messy -- sorry! Highlights:
- We already use Zulip ID as the database key.
Ignore the "id" value in the database *value*, since it's redundant with the record ID.
Alongside this, I slightly refactored how the record-to-struct conversion happens.
- Use the Zulip ID when sending messages.
Empirically, list of IDs has to be given as `[123,456]`,
i.e. with square brackets. It's fine to send a single-receiver message as `[123]`
(Jeremy got the "odd one out" message).
- Retrieve the Zulip ID from the RC API, to use when handling end-of-batch processing

Use Zulip ID instead of email for most purposes

---

.gitignore

The main reason for this PR is that the `.*` glob was causing some of my dev tools to miss the `.github` directory even though it *is* committed to the repo. That's the only line I *really* want to remove.
While I was here, I also removed the lines related to files that I didn't recognize. I'll gladly add any back in if they're important to common workflows, but I think most of these would make more sense in local repo config (the `.git/info/exclude` file) or in user-level Git config (the `core.excludesFile` setting).

dev: Clean up .gitignore

---

.github/workflows/go.yml
database_test.go
dev.sh

I want to be able to experiment with Pairing Bot locally, which means I'll need some way to run Firestore without also running all of Google Cloud. It turns out that there's an [emulator](https://cloud.google.com/firestore/docs/emulator) inside of `gcloud` which is made exactly for this purpose!
The Firestore Go SDK we're using automatically supports using this via the `FIRESTORE_EMULATOR_HOST` environment variable.
This sets up a single round-trip test to prove that this all works. I left space to add more because I'll be collecting them in the future as I learn about how Firestore works (and how we use it!).
I also made these tests run on PRs to the `dev` branch. I intend to treat them as non-blocking there, but I do think it's nice to know that we've broken unit tests before deploying, …

dev: Add round-trip test for Recurser collection

---

database.go

The cron jobs failed to run today because PB panicked while trying to un-skip someone for tomorrow.
[Zulip report](https://recurse.zulipchat.com/#narrow/stream/26440-small-questions/topic/pairing.20bot.20not.20matching.3F/near/462347012)
```
2024/08/14 04:00:01 server.go:3418: http: panic serving 127.0.0.1:38996: interface conversion: interface {} is int64, not string
...
main.(*FirestoreRecurserDB).UnsetSkippingTomorrow(0xc000062440, {0xcf20f8, 0xc00042c0a0}, {0xb2144, {0xc0004f62e0, 0x1b}, {0xc0001408b8, 0x17}, 0x1, 0xc0001e7080, ...})
/layers/google.go.appengine-gomod/srv/database.go:254 +0x4a5
main.(*PairingLogic).match(0xc0000a6980, {0xcf0d70, 0xc00009e000}, 0xc000496000)
/layers/google.go.appengine-gomod/srv/pairing_bot.go:136 +0x425
...
```
It looks like the issue is the assumption …

fix: Assume recurser ID is an int and document ID is a string

---

main.go

The Firestore client maintains its own internal gRPC connection pool and allows for its methods to be called concurrently. So we should be able to create just one client and reuse it everywhere we run Firestore queries.
Before, we were creating one client per collection, but all of them have identical configuration. From a quick skim through history, I don't think this was done for any isolation or performance reasons, and most endpoints access multiple collections anyway. So I want to try simplifying app startup by having just the one client.
I'll manually trigger a pairing job in the dev project and send the test bot some config requests.

fix: Use one Firestore connection pool for all collections

---

pairing_bot.go

Per report in Zulip, it seems like one Recurser has repeatedly been the
odd-one-out, i.e. the Recurser at the end of the list.
Prior to this change, the only entropy came from the start time. I don't
know whether that is considered a "good" seed; I'm suspicious that it
will have many bits the same from one day to another, and that could
result in some of the weirdness mentioned by a recurser.
With this change:
- Get a seed from the default randomness source.
- Log the seed, so (if we need to later debug a shuffle) we can patch it
in. (In principle - ofc we'd have to run Pairing Bot locally for
that...)
- Use that seed to create the shuffling RNG.
As I understand it, "seed a thread-local RNG from a thread-safe RNG" is
a pretty standard practice, and is relatively entropy-preserving.

Log the random seed; use a random seed

---

dispatch.go
dispatch_test.go
main.go
pairing_bot.go
parse_cmd.go
parse_cmd_test.go

This reads the Google App Engine version from the environment and returns it in response to a new `version` command.
Ideally, we'd be able to get the current commit hash, but I haven't figured out a nice way to make that work through Cloud Build + App Engine. I suspect the answer is to start pushing our own Docker images, and that's something I don't want to do yet.
Since we don't currently name our GAE versions, we get timestamps (like `20240904t202224`). That's still good enough to show the difference between two builds.

feat: Add version command

---

.github/workflows/go.yml
.golangci.toml
api.go
database.go

There are a lot of Go linters out there that have saved me at least once, so I'd like to start running them here!
You can see what the report looks like on https://github.com/recursecenter/pairing-bot/pull/80/files
---
- **dev: Add golangci-lint step to Go workflow**
- **fix: Log unhandled errors**
- **refactor: Remove unused DB mocks**

dev: Add golangci-lint to Go workflow

---

database.go
database_test.go
dispatch.go
main.go
pairing_bot.go

This is the same as #81 but applied to the much smaller `FirestoreAPIAuthDB`.
The app treats these as read-only because they're essentially config secrets.
We always ask for them by full name, and those names are static strings, so I chose to use the full path as the argument instead of splitting the collection out like the previous interface.
With the test bot, do something that requires loading each of the three tokens:
- These three collections (`apiauth`, `botauth`, `rc-accesstoken`) each contain a single document. I want to merge them into a `secrets` or `config` collection so that they're easier to keep track of.
- Continue doing this for more collections!

refactor: Use Firestore struct tags for auth tokens

---

dispatch.go
pairing_bot.go

There are three of us now! Every `==` check on Zulip ID now becomes a set-membership check, and we have to do a little bit of extra work to tag us all at once.
I learned that Zulip allows tagging by ID-only if you use its disambiguation syntax directly. For example, these three all produce the same mention-chip for me:
```
@_**|720507**
@_**Jeremy Kaplan (he) (S1'24)**
@_**Jeremy Kaplan (he) (S1'24)|720507**
```
This means we don't have to keep track of display names at all anymore. This avoids desyncs due to display name changes (including batch assignments).

fix: Update maintainers list

---

pairing_bot.go

I had trouble understanding the maintenance mode condition, so I wrote a function for checking whether someone is a maintainer. This makes the condition more readable!

refactor: Add isMaintainer function

---

dispatch.go
dispatch_test.go
pairing_bot.go

While reading the `dispatch` function to learn how it works, I realized that all the switch cases are independent and don't really depend on the shared `response` and `err` variables. To make this clearer, I've given each command a dedicated method on `PairingLogic` and used those as case bodies.
This also gives us better testing hooks for individual commands, although I haven't written those tests yet.
Along the way, I discovered that my previous changes had dropped the "db error, ping someone" response, so this restores that too.
I recommend reviewing this by commits instead of all at once! I organized the changes as a bunch of tiny refactors that should be easy to verify because this code is currently hard to test.
These are all the non-refactor commits (i.e., behavior changes):
- …

refactor: Split dispatch into smaller functions

---

pairing_bot.go
parse_cmd.go
parse_cmd_test.go

I wanted to understand the parser tests better, so I collected them into good/bad groups and added some more cases that weren't tested before.

dev: Add more tests for parseCmd

---

go.mod
internal/assert/assert.go
parse_cmd_test.go
recurse/client.go
recurse/client_test.go
zulip/client_test.go

After the third copy-paste of assertEqual, I think it's time to make an internal test assertion library.
This is similar to [testify]'s assert package, mostly because it's the one I'm most familiar with.
This now uses [go-cmp] instead of `reflect.DeepEqual` for comparing values. We get free diff reports out of it too!
I added the package to a new `internal` directory to make it clear that this isn't part of the application itself. It also prevents it from being imported from anywhere else, even though there's no reason to import from this module anyway.
[go-cmp]: https://github.com/google/go-cmp
[testify]: https://github.com/stretchr/testify

refactor: Extract assert package from existing tests

---

internal/assert/assert.go
pairing_bot.go
parse_cmd.go
parse_cmd_test.go

This is the big parser rewrite! I tried to do it in small chunks, but I relied a lot on the now-nearly-exhaustive test suite.

refactor: Rewrite the command parser

---

database.go
database_test.go
dispatch.go
pairing_bot.go

This annotates the `Review` type with Firestore struct tags to make it easier to map back and forth between the struct and the document contents. This follows the pattern set by #81 and #82.
This also changes the `Timestamp` field from `int` to `int64` to match both places the type is relevant:
- Firestore represents integers as `int64`.
- The timestamps are Unix epoch times from Go's `time` library, which are also represented as `int64`.

refactor: Use Firestore struct tags for reviews

---

main.go
pairing_bot.go

Google Cloud supports [log-based alerts], especially if we start adding interesting fields to our logs (such as severity levels). The Go standard library now provides `log/slog` for structured (and leveled) logging, so let's start using it!
By default, the `slog` default logger also handles unstructured logs and emits them at "INFO" level. That's exactly what I would have done for most of our logs anyway, so we don't immediately have to change any code we already have.
But I _did_ choose to change one place: end-of-batch has a `log.Fatal` which is the same as `log.Info` + `os.Exit(1)`. Rather than exiting the whole process, I'd rather have it emit an error-level log and alert us. I also made it return an HTTP 500 response, so it still shows up as a failed cron job run.
[log-based alerts]: …

dev: Switch to leveled logging for alerts

---

database.go
database_test.go
pairing_bot.go

This is the last collection for struct tag refactoring - `FirestorePairingsDB` - which closes #83!
- A new struct type `Pairing` is added on similar lines to the `Review` and `Recurser`  structs. This changes the parameters of `SetNumPairings` to use the new type. 
- The `Timestamp` field is changed from `int` to `int64` as both Go and Firestore store this value as `int64`, leading to fewer conversions.
I thought of using `fetchAll` in `GetTotalPairingsFromLastWeek` since the code is nearly the same. However using it would mean having to loop twice (once in `fetchAll` and once to add the pairing values), so I kept the function as is.

refactor: Use Firestore struct tags for pairings

---

main.go
pairing_bot.go

Pairing Bot's welcome topic has been moved from "397 Bridge" to "current batches", so it's time to update the code to start posting there instead.
The test bot's posts get printed to the logs instead of actually being sent to Zulip. But just in case (or for some more realistic future integration testing?), I set the test bot welcome stream destination to the shared "test-bot" stream.

fix: Move the welcome message to "current batches"

---

main.go
pairing_bot.go

Pairing Bot holds many secrets, and some of them are config values!
Right now, those config secrets are stored in single-document collections that (in my experience) have names that don't clearly map to their usage.
This starts reading them all out of a new collection named "secrets", and each document contains a single secret token.
I've already copied the secrets to their new locations, which can be verified in the Google Cloud console for both environments. (The RC API access token won't match, though, because I generated a new one out of my RC account.)
After both the dev and prod bots deploy successfully, I'll delete the old unused secret collections.

fix: Read secrets from new collection

---

main.go
middleware.go
middleware_test.go
pairing_bot.go

This de-duplicates the code we have to check the AppEngine Cron request header and pushes it into the HTTP router and out of the app logic.
As a convenient side effect, this also ensures that any cron job failure produces an HTTP 500 response (indicating failure to AppEngine) and an ERROR-severity log line (which we're starting to use for alerts).

refactor: Extract AppEngine Cron source check into middleware

---

main.go
pairing_bot.go

Just a tiny change that @jdkaplan suggested to make `maintenanceMode` non-global.

Move maintenanceMode to the PairingLogic struct

---

dispatch.go
dispatch_test.go
messages.go
parse_cmd.go
parse_cmd_test.go

Another tiny one. This time, I have the test suite running. I'll try something a bit meatier in the next PR.
closes #89

Responding to "Thanks" with "You're welcome!"

---

main.go

I thought that the current batches channel name was just the text, but it really does include the emoji!
I found this out because Zulip messaged me this when PB tried to check in today:
> Your bot 'pairing-bot@recurse.zulipchat.com' tried to send a message to channel #**current batches**, but that channel does not exist. Click [here]() to create it.
I'll re-run the welcome job after merging.
For anyone with Google Cloud access, there's also [this alert](https://console.cloud.google.com/monitoring/alerting/alerts/0.njzjgu5x8ny0?channelType=mail&project=pairing-bot-284823) when the job failed. Yay, monitoring!

fix: Use correct welcome stream name

---

go.mod

- chore: go module upgrade
- chore: upgrade go version
Since apparently the just-module rev didn't build.

Go version upgrade

---

cloudbuild.yaml

This caused the prod push to fail. D'oh.

fix: Remove overzealous pinning (gcloud doesn't have a version 1.22
